function compare_dep(d_qis, d_cor, d_rdc, line)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This function prints respective rows of direct influence matrices
% generated by QIS, COR, and RDC methods in a table for specified line.
% Each section is sorted in descending order.
% INPUTS:
%  -d_qis: Direct influence matrix generated by QIS (causation) method
%  -d_cor: Direct influence matrix generated by normalized correlation
%  method
%  -d_rdc: Direct influence matrix generated by RDC method
%  -line: Transmission line whose influences on other components are to be
%  compared.
%
% Author:            Koosha Marashi
% Email:             km89f@mst.edu
% First version:     December 1, 2016
% Copyright (C) SeNDeComp Group, Missouri S&T
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

[d_qis_sorted, d_qis_sorted_idx] = sort(d_qis(line, :), 'descend');
[d_cor_sorted, d_cor_sorted_idx] = sort(d_cor(line, :), 'descend');
[d_rdc_sorted, d_rdc_sorted_idx] = sort(d_rdc(line, :), 'descend');
header = sprintf('Causation\t\t||\tN-Correlation\t||\tRDC\n');
header = [repmat('-', 1, 53), sprintf('\n'), ...
    header, repmat('-', 1, 53), sprintf('\n')];
str = [header, ...
    sprintf('%.0f\t|\t%.3f\t||\t%.0f\t|\t%.3f\t||\t%.0f\t|\t%.3f\n', ...
    [d_qis_sorted_idx; d_qis_sorted; ...
    d_cor_sorted_idx; d_cor_sorted; ...
    d_rdc_sorted_idx; d_rdc_sorted])];
disp(str)

end